### ISSUE TITLE
qc.snakefile 

### ISSUE THREAD

**Issue by camel315** [pnnl/atlas#70]
@brwnj There is probably an error in line 407 of qc.snakefile. Please check.
rule calculate_insert_size:
    input: OD3/sequence_quality_control/OD3_QC_R2.fastq.gz, OD3/sequence_quality_control/OD3_QC_R1.fastq.gz, OD3/sequence_quality_control/OD3_QC_se.fastq.gz
    output: OD3/sequence_quality_control/read_stats/QC_insert_size_hist.txt, OD3/sequence_quality_control/read_stats/QC_read_length_hist.txt
    log: OD3/logs/OD3_calculate_insert_size.log
    jobid: 4
    benchmark: logs/benchmarks/merge_pairs/OD3_insert_size.txt
    wildcards: sample=OD3

    threads: 24
    resources: mem=72

bbmerge.sh -Xmx60G threads=36                    in1=OD3/sequence_quality_control/OD3_QC_R1.fastq.gz in2=OD3/sequence_quality_control/OD3_QC_R2.fastq.gz                    ecct k=62                    extend2=50                    ihist=OD3/sequence_quality_control/read_stats/QC_insert_size_hist.txt merge=f                    mininsert0=35 minoverlap0=8 2> >(tee OD3/logs/OD3_calculate_insert_size.log)
                
                readlength.sh in=OD3/sequence_quality_control/OD3_QC_R1.fastq.gz in2=OD3/sequence_quality_control/OD3_QC_R2.fastq.gz out=OD3/sequence_quality_control/read_stats/QC_read_length_hist.txt 2> >(tee OD3/logs/OD3_calculate_insert_size.log)
            
Activating conda environment /panfs/panfs14.gfz-hpcc.cluster/home/gmb/syang/results/.snakemake/conda/dbc7d302.
Error in rule calculate_insert_size:
    jobid: 4
    output: OD3/sequence_quality_control/read_stats/QC_insert_size_hist.txt, OD3/sequence_quality_control/read_stats/QC_read_length_hist.txt
    log: OD3/logs/OD3_calculate_insert_size.log

RuleException:
CalledProcessError in line 407 of /home/syang/anaconda3/lib/python3.5/site-packages/atlas/rules/qc.snakefile:
Command 'source activate /home/syang/results/.snakemake/conda/dbc7d302; set -euo pipefail;  bbmerge.sh -Xmx60G threads=36                    in1=OD3/sequence_quality_control/OD3_QC_R1.fastq.gz in2=OD3/sequence_quality_control/OD3_QC_R2.fastq.gz                    ecct k=62                    extend2=50                    ihist=OD3/sequence_quality_control/read_stats/QC_insert_size_hist.txt merge=f                    mininsert0=35 minoverlap0=8 2> >(tee OD3/logs/OD3_calculate_insert_size.log)
                
                readlength.sh in=OD3/sequence_quality_control/OD3_QC_R1.fastq.gz in2=OD3/sequence_quality_control/OD3_QC_R2.fastq.gz out=OD3/sequence_quality_control/read_stats/QC_read_length_hist.txt 2> >(tee OD3/logs/OD3_calculate_insert_size.log) ' returned non-zero exit status 1
  File "/home/syang/anaconda3/lib/python3.5/site-packages/atlas/rules/qc.snakefile", line 407, in __rule_calculate_insert_size
  File "/home/syang/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/syang/.snakemake/log/2017-12-20T232825.193914.snakemake.log
[2017-12-20 23:31 CRITICAL] Command 'snakemake --snakefile /home/syang/anaconda3/lib/python3.5/site-packages/atlas/Snakefile --directory /home/syang/results --printshellcmds --jobs 24 --rerun-incomplete --configfile '/home/syang/config.yaml' --nolock --use-conda  --config workflow=complete  --latency-wait 240 --until calculate_insert_size' returned non-zero exit status 1

_Even after setting the prealloc=t for the tadpole.sh which is involved in rule calculate_insert_size within qc.snakefile, it still report 'run out of memory'_

Exception in thread "Thread-8" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at ukmer.KmerNodeU.<init>(KmerNodeU.java:22)
        at ukmer.KmerNodeU1D.<init>(KmerNodeU1D.java:22)
        at ukmer.HashForestU.makeNode(HashForestU.java:47)
        at ukmer.HashForestU.makeNode(HashForestU.java:43)
        at ukmer.HashForestU.incrementAndReturnNumCreated(HashForestU.java:130)
        at ukmer.HashArrayU1D.incrementAndReturnNumCreated(HashArrayU1D.java:72)
        at ukmer.HashBufferU.dumpBuffer_inner(HashBufferU.java:196)
        at ukmer.HashBufferU.dumpBuffer(HashBufferU.java:168)
        at ukmer.HashBufferU.incrementAndReturnNumCreated(HashBufferU.java:57)
        at ukmer.KmerTableSetU$LoadThread.addKmersToTable(KmerTableSetU.java:553)
        at ukmer.KmerTableSetU$LoadThread.run(KmerTableSetU.java:479)
Exception in thread "Thread-26" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at ukmer.KmerNodeU.<init>(KmerNodeU.java:22)
        at ukmer.KmerNodeU1D.<init>(KmerNodeU1D.java:22)
        at ukmer.HashForestU.makeNode(HashForestU.java:47)
        at ukmer.HashForestU.makeNode(HashForestU.java:43)
        at ukmer.HashForestU.incrementAndReturnNumCreated(HashForestU.java:130)
        at ukmer.HashArrayU1D.incrementAndReturnNumCreated(HashArrayU1D.java:72)
        at ukmer.HashBufferU.dumpBuffer_inner(HashBufferU.java:196)
        at ukmer.HashBufferU.dumpBuffer(HashBufferU.java:168)
        at ukmer.HashBufferU.incrementAndReturnNumCreated(HashBufferU.java:57)
        at ukmer.KmerTableSetU$LoadThread.addKmersToTable(KmerTableSetU.java:553)
        at ukmer.KmerTableSetU$LoadThread.run(KmerTableSetU.java:489)
Exception in thread "Thread-3" Exception in thread "Thread-14" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at ukmer.KmerNodeU.<init>(KmerNodeU.java:22)
        at ukmer.KmerNodeU1D.<init>(KmerNodeU1D.java:22)
        at ukmer.HashForestU.makeNode(HashForestU.java:47)
        at ukmer.HashForestU.makeNode(HashForestU.java:43)
        at ukmer.HashForestU.incrementAndReturnNumCreated(HashForestU.java:130)
        at ukmer.HashArrayU1D.incrementAndReturnNumCreated(HashArrayU1D.java:72)
        at ukmer.HashBufferU.dumpBuffer_inner(HashBufferU.java:196)
        at ukmer.HashBufferU.dumpBuffer(HashBufferU.java:168)
        at ukmer.HashBufferU.incrementAndReturnNumCreated(HashBufferU.java:57)
        at ukmer.KmerTableSetU$LoadThread.addKmersToTable(KmerTableSetU.java:553)
        at ukmer.KmerTableSetU$LoadThread.run(KmerTableSetU.java:489)
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at ukmer.HashForestU.makeNode(HashForestU.java:47)
        at ukmer.HashForestU.makeNode(HashForestU.java:43)
        at ukmer.HashForestU.incrementAndReturnNumCreated(HashForestU.java:130)
        at ukmer.HashArrayU1D.incrementAndReturnNumCreated(HashArrayU1D.java:72)
        at ukmer.HashBufferU.dumpBuffer_inner(HashBufferU.java:196)
        at ukmer.HashBufferU.dumpBuffer(HashBufferU.java:168)
        at ukmer.HashBufferU.incrementAndReturnNumCreated(HashBufferU.java:57)
        at ukmer.KmerTableSetU$LoadThread.addKmersToTable(KmerTableSetU.java:553)
        at ukmer.KmerTableSetU$LoadThread.run(KmerTableSetU.java:479)
Exception in thread "Thread-19" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-28" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-27" Exception in thread "Thread-9" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded

This program ran out of memory.
Try increasing the -Xmx flag and using tool-specific memory-related parameters. 

Any solutions? Thank you.

**Comment by camel315** [comment]
Solved. This step will call tadpole.sh, which provides several parameters to avoid running out of memory. I just added prealloc=t,  prefilter=t, and minprob=0.8 in the corresponding lines in qc.snakefile. Now it worked for me.

**Comment by SilasK** [comment]
@camel315  thank you. I added `prealloc=t  prefilter=t` to the rule `calculate_insert_size` on my branch `silas`, which will be integrated soon into the master.

**Comment by brwnj** [comment]
Thanks @camel315, we integrated this fix in c8952cd00253c2c8176b7d2e3bf39bf93c639b72.
