### ISSUE TITLE
Unicode&snakemake problems while setting up atlas

### ISSUE THREAD

**Issue by LottaP** [pnnl/atlas#8]
Hi! I'm having trouble setting up atlas to my Macbook pro (OSX El Capitan 10.11.6). After initially trying to install atlas with pip, ran into this:

```
    return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2365: ordinal not in range(128)
```

but yesterday installation went through but now I'm getting this error when downloading databases:

```
Traceback (most recent call last):
  File "/Users/lplotta/miniconda3/bin/atlas", line 11, in <module>
    sys.exit(cli())
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
```

Similar (?) issue is raised when trying to look into atlas executable for example with atlas --version

```
Traceback (most recent call last):
  File "/Users/lplotta/miniconda3/bin/atlas", line 11, in <module>
    sys.exit(cli())
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
```

ALSO: previously had this error when trying to download databases:

```
[2017-05-09 09:54] Executing: snakemake -s /Users/lplotta/miniconda3/lib/python3.5/site-packages/atlas/Snakefile -d / -p -j 8 --nolock --rerun-incomplete --config db_dir='/databases' workflow=download -- 
Traceback (most recent call last):
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/snakemake/__init__.py", line 426, in snakemake
    force_use_threads=use_threads)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/snakemake/workflow.py", line 317, in execute
    list_params_changes)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/snakemake/persistence.py", line 24, in __init__
    os.mkdir(self.path)
PermissionError: [Errno 13] Permission denied: '/.snakemake'
Traceback (most recent call last):
  File "/Users/lplotta/miniconda3/bin/atlas", line 11, in <module>
    sys.exit(cli())
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/atlas/atlas.py", line 308, in run_download
    download(jobs, out_dir, snakemake_args)
  File "/Users/lplotta/miniconda3/lib/python3.5/site-packages/atlas/workflows.py", line 42, in download
    check_call(cmd, shell=True)
  File "/Users/lplotta/miniconda3/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'snakemake -s /Users/lplotta/miniconda3/lib/python3.5/site-packages/atlas/Snakefile -d / -p -j 8 --nolock --rerun-incomplete --config db_dir='/databases' workflow=download -- ' returned non-zero exit status 1
```

**Comment by brwnj** [comment]
To deal with the first 3 issues, from `click` documentation:

> You are dealing with an environment where Python 3 thinks you are restricted to ASCII data. The solution to these problems is different depending on which locale your computer is running in.
> 
> For instance, if you have a German Linux machine, you can fix the problem by exporting the locale to de_DE.utf-8:
> 
> export LC_ALL=de_DE.utf-8
> export LANG=de_DE.utf-8
> 
> If you are on a US machine, en_US.utf-8 is the encoding of choice. On some newer Linux systems, you could also try C.UTF-8 as the locale:
> 
> export LC_ALL=C.UTF-8
> export LANG=C.UTF-8

Then, as we're using `maxbin2` for genomic binning, that makes this protocol incompatible with macOS at this time. If at some point someone gets `fraggenescan` to work on macOS then we can add the operating system.

I can't explain the last one. It has to do with your environment for sure, but not sure why `snakemake` isn't executable to you. Does `snakemake --help` work? What are the permissions on `snakemake`?

**Comment by brwnj** [comment]
I wanted to add that I'm working on a major new release for our publication submission and will make genomic binning optional. Having it optional would make most of the protocol work on macOS, but you're still going to be RAM limited.

**Comment by brwnj** [comment]
We have addressed these issues in the latest release to an extent. The final issue you list was not related to the package itself, rather it's complaining because you don't have permission to write in the root directory. I've updated the documentation so examples, if copied directly, now write into the user's home directory.
